create table "client"
(
    "id" bigint generated by default as identity primary key,
    "name" varchar(50) not null
);

create table "address"
(
    "id" bigint generated by default as identity primary key,
    "street" varchar(255) not null,
    "client_id" bigint not null unique,
    constraint fk_address_client foreign key ("client_id") references "client" ("id")
);

create table "phone"
(
    "id" bigint generated by default as identity primary key,
    "number" varchar(30) not null,
    "phone_order" integer not null,
    "client_id" bigint not null,
    constraint fk_phone_client foreign key ("client_id") references "client" ("id")
);
